import Groq from 'groq-sdk';
import { cacheService } from '../redis/cache.service.js';

export interface AIExplanationPayload {
  algorithm: string;
  currentStep: any;
  previousStep?: any;
  nextStep?: any;
  code?: string;
  pseudocode?: string;
  question?: string;
}

const SYSTEM_PROMPT = `You are AlgoLens Tutor.
You are a patient, encouraging computer science teacher.
The execution trace supplied by the backend is the absolute source of truth.

Rules:
- NEVER invent array states, variable values, tree states, code execution, or algorithm results.
- Only explain information contained in the supplied execution context.
- Keep your explanation structured, concise, and pedagogical:
  1. What happened in this step?
  2. Why did it happen according to the algorithm rules?
  3. Which code line caused it?
  4. Which variables changed?
  5. What changed visually on the screen?
  6. What happens next?
- Use simple, beginner-friendly language with clear markdown formatting.`;

class AIService {
  private groqClient: Groq | null = null;

  constructor() {
    const apiKey = process.env.GROQ_API_KEY;
    if (apiKey && apiKey !== 'gsk_your_groq_api_key_here') {
      this.groqClient = new Groq({ apiKey });
      console.log('[Groq] AI Tutor service initialized.');
    } else {
      console.log('[Groq] GROQ_API_KEY not configured. Running with pedagogical rule-based fallback.');
    }
  }

  public async explainStep(payload: AIExplanationPayload): Promise<{
    explanation: string;
    source: 'groq' | 'cache' | 'fallback';
  }> {
    const cacheKey = cacheService.generateKey(
      `ai:${payload.algorithm}:${payload.currentStep?.id}`,
      payload.question || 'general'
    );

    // 1. Check cache first
    const cached = await cacheService.get<string>(cacheKey);
    if (cached) {
      return { explanation: cached, source: 'cache' };
    }

    // 2. Query Groq if available
    if (this.groqClient) {
      try {
        const userPrompt = `Algorithm: ${payload.algorithm}
Current Step #${payload.currentStep?.id}: "${payload.currentStep?.title}"
Description: ${payload.currentStep?.description}
Algorithm Line: ${payload.currentStep?.algorithmLine}
Code Line: ${payload.currentStep?.codeLine ?? 'N/A'}
Variables: ${JSON.stringify(payload.currentStep?.variables ?? {})}
Comparisons: ${JSON.stringify(payload.currentStep?.comparisons ?? {})}
Array/Structure State: ${JSON.stringify(payload.currentStep?.arrayState ?? payload.currentStep?.dataStructureState ?? {})}
Previous Step Title: ${payload.previousStep?.title ?? 'None (Start)'}
Next Step Title: ${payload.nextStep?.title ?? 'None (End)'}

Student Question: ${payload.question || 'Can you explain this step clearly and why it occurred?'}`;

        const chatCompletion = await this.groqClient.chat.completions.create({
          messages: [
            { role: 'system', content: SYSTEM_PROMPT },
            { role: 'user', content: userPrompt },
          ],
          model: process.env.GROQ_MODEL || 'openai/gpt-oss-120b',
          temperature: 0.2,
          max_tokens: 600,
        });

        const explanation =
          chatCompletion.choices[0]?.message?.content ||
          'No explanation generated by AI tutor.';

        // Cache for 24 hours
        await cacheService.set(cacheKey, explanation, 86400);

        return { explanation, source: 'groq' };
      } catch (err: any) {
        console.warn('[Groq] API request error, falling back to rule-based explanation:', err.message);
      }
    }

    // 3. Deterministic Pedagogical Fallback
    const fallback = this.generateFallbackExplanation(payload);
    return { explanation: fallback, source: 'fallback' };
  }

  public async generatePersonalizedQuestion(
    params: {
      userId: string;
      algorithmId?: string;
      topic?: string;
      completedAlgorithms?: string[];
      weakAlgorithms?: string[];
      recentErrors?: string[];
    }
  ): Promise<{
    id: string;
    algorithmId: string;
    title: string;
    question: string;
    options: { id: string; text: string; isCorrect: boolean }[];
    explanation: string;
    difficulty: string;
    pedagogicalReason: string;
    source: 'groq' | 'fallback';
  }> {
    const targetAlgo =
      params.algorithmId ||
      (params.weakAlgorithms && params.weakAlgorithms.length > 0
        ? params.weakAlgorithms[0]
        : 'merge-sort');

    if (this.groqClient) {
      try {
        const prompt = `Student User ID: ${params.userId}
Target Algorithm / Topic: ${targetAlgo}
Completed Algorithms: ${(params.completedAlgorithms || []).join(', ') || 'None yet'}
Weak Topics (Struggled with): ${(params.weakAlgorithms || []).join(', ') || 'None reported'}
Recent Quiz Errors: ${(params.recentErrors || []).join('; ') || 'No recorded errors'}

Create a targeted, educational multiple-choice DSA quiz question for this student. Focus on their misconception or testing their understanding of edge cases/rotations/invariants for ${targetAlgo}.
Return strict JSON with fields: id, algorithmId, title, question, options (4 objects with { id: "a"|"b"|"c"|"d", text, isCorrect }), explanation, difficulty ("Easy"|"Medium"|"Hard"), pedagogicalReason.`;

        const completion = await this.groqClient.chat.completions.create({
          model: process.env.GROQ_MODEL || 'openai/gpt-oss-120b',
          messages: [
            {
              role: 'system',
              content:
                'You are an expert Computer Science professor generating personalized DSA practice questions for university students. You must output ONLY valid JSON matching the requested structure.',
            },
            { role: 'user', content: prompt },
          ],
          temperature: 0.3,
          response_format: { type: 'json_object' },
        });

        const rawContent = completion.choices[0]?.message?.content;
        if (rawContent) {
          const parsed = JSON.parse(rawContent);
          if (parsed.question && Array.isArray(parsed.options) && parsed.options.length >= 2) {
            return {
              id: parsed.id || `ai-${Date.now()}`,
              algorithmId: parsed.algorithmId || targetAlgo,
              title: parsed.title || `${targetAlgo} Mastery Check`,
              question: parsed.question,
              options: parsed.options,
              explanation: parsed.explanation || 'No explanation provided.',
              difficulty: parsed.difficulty || 'Medium',
              pedagogicalReason:
                parsed.pedagogicalReason ||
                `Personalized for your progress in ${targetAlgo}.`,
              source: 'groq',
            };
          }
        }
      } catch (err: any) {
        console.warn('[Groq] Personalized question generation error:', err.message);
      }
    }

    // Deterministic Fallback Question
    return {
      id: `fallback-${Date.now()}`,
      algorithmId: targetAlgo,
      title: `${targetAlgo.toUpperCase()} Core Concept Check`,
      question: `In ${targetAlgo}, which statement best characterizes its runtime invariant or operational property?`,
      options: [
        { id: 'a', text: `It guarantees optimal state transitions with documented worst-case bounds.`, isCorrect: true },
        { id: 'b', text: `It always executes in O(1) space regardless of inputs.`, isCorrect: false },
        { id: 'c', text: `It does not require comparisons or state transitions.`, isCorrect: false },
        { id: 'd', text: `It only works on inputs of size less than 10.`, isCorrect: false },
      ],
      explanation: `Each algorithm in AlgoLens maintains strict invariants ensuring formal correctness and bounded asymptotic complexity.`,
      difficulty: 'Medium',
      pedagogicalReason: `Personalized review generated for ${targetAlgo} to reinforce foundational algorithmic properties.`,
      source: 'fallback',
    };
  }

  private generateFallbackExplanation(payload: AIExplanationPayload): string {
    const step = payload.currentStep;
    if (!step) {
      return 'No active execution step found to explain.';
    }

    const varList = Object.entries(step.variables || {})
      .map(([k, v]) => `• **${k}**: \`${v}\``)
      .join('\n');

    return `### 💡 AlgoLens Tutor Explanation

**Step ${step.id}: ${step.title}**

1. **What happened?**
${step.description}

2. **Why did it happen?**
This step executed according to the core logic of **${payload.algorithm.toUpperCase()}** at algorithm line **${step.algorithmLine}**.
${step.comparisons ? `The comparison evaluation was: \`${step.comparisons.result}\`.` : 'State transition completed based on active loop invariants.'}

3. **Active Variables:**
${varList || '• No local variables mutated in this step.'}

4. **Visual Change:**
${step.highlights && step.highlights.length > 0 ? `Indices [${step.highlights.join(', ')}] are highlighted to reflect current pointer positions and active comparisons.` : 'The data structure updated its state.'}

5. **What happens next?**
${payload.nextStep ? `Next operation: **${payload.nextStep.title}** (${payload.nextStep.description})` : 'This is the final state of the algorithm. Execution has concluded successfully.'}`;
  }
}

export const aiService = new AIService();
