import Groq from 'groq-sdk';
import { cacheService } from '../redis/cache.service.js';

export interface AIExplanationPayload {
  algorithm: string;
  currentStep: any;
  previousStep?: any;
  nextStep?: any;
  code?: string;
  pseudocode?: string;
  question?: string;
}

const SYSTEM_PROMPT = `You are the AlgoLens Senior AI Tutor — an expert computer science educator and staff engineer.

Your goal is to provide concise, human-understandable, and professional explanations of algorithm execution steps.

STRICT WRITING GUIDELINES:
- DO NOT use conversational filler, cheesy greetings ("Hello! 👋", "Let's walk through..."), or sign-offs. Jump straight into the explanation.
- DO NOT generate giant markdown tables of raw variables or repeat values already displayed in the UI panels.
- DO NOT output unrendered raw LaTeX blocks like \\[ \\text{mid} = \\dots \\]; use clean inline math (e.g. "mid = (0 + 1) / 2 = 0").
- Never leave truncated sentences or trailing fragments.
- Speak directly, like a top-tier senior engineer explaining code to a peer or student.
- Format strictly with these 3 clean sections:
  ### 🎯 Core Action
  1-2 concise, plain-English sentences stating what happened in this step.

  ### 💡 Intuition & Logic
  Explain why the algorithm made this choice (the condition, formula, invariant, or comparison that triggered it).

  ### ⏭️ What to Watch Next
  1 sentence explaining what the algorithm focuses on in the immediate next step.

- If the student asked a custom question, add an initial "### 💬 Answer" section addressing their question directly in 1-2 sharp paragraphs before the intuition.`;

class AIService {
  private groqClient: Groq | null = null;

  constructor() {
    const apiKey = process.env.GROQ_API_KEY;
    if (apiKey && apiKey !== 'gsk_your_groq_api_key_here') {
      this.groqClient = new Groq({ apiKey });
      console.log('[Groq] AI Tutor service initialized.');
    } else {
      console.log('[Groq] GROQ_API_KEY not configured. Running with pedagogical rule-based fallback.');
    }
  }

  public async explainStep(payload: AIExplanationPayload): Promise<{
    explanation: string;
    source: 'groq' | 'cache' | 'fallback';
  }> {
    const cacheKey = cacheService.generateKey(
      `ai:v3:${payload.algorithm}:${payload.currentStep?.id}`,
      payload.question || 'general'
    );

    // 1. Check cache first
    const cached = await cacheService.get<string>(cacheKey);
    if (cached) {
      return { explanation: cached, source: 'cache' };
    }

    // 2. Query Groq if available
    if (this.groqClient) {
      try {
        const userPrompt = `Algorithm: ${payload.algorithm}
Current Step #${payload.currentStep?.id}: "${payload.currentStep?.title}"
Description: ${payload.currentStep?.description}
Algorithm Line: ${payload.currentStep?.algorithmLine}
Code Line: ${payload.currentStep?.codeLine ?? 'N/A'}
Variables: ${JSON.stringify(payload.currentStep?.variables ?? {})}
Comparisons: ${JSON.stringify(payload.currentStep?.comparisons ?? {})}
Array/Structure State: ${JSON.stringify(payload.currentStep?.arrayState ?? payload.currentStep?.dataStructureState ?? {})}
Previous Step Title: ${payload.previousStep?.title ?? 'None (Start)'}
Next Step Title: ${payload.nextStep?.title ?? 'None (End)'}

Student Question: ${payload.question || 'Can you explain this step clearly and why it occurred?'}`;

        const chatCompletion = await this.groqClient.chat.completions.create({
          messages: [
            { role: 'system', content: SYSTEM_PROMPT },
            { role: 'user', content: userPrompt },
          ],
          model: process.env.GROQ_MODEL || 'openai/gpt-oss-120b',
          temperature: 0.2,
          max_tokens: 600,
        });

        const explanation =
          chatCompletion.choices[0]?.message?.content ||
          'No explanation generated by AI tutor.';

        // Cache for 24 hours
        await cacheService.set(cacheKey, explanation, 86400);

        return { explanation, source: 'groq' };
      } catch (err: any) {
        console.warn('[Groq] API request error, falling back to rule-based explanation:', err.message);
      }
    }

    // 3. Deterministic Pedagogical Fallback
    const fallback = this.generateFallbackExplanation(payload);
    return { explanation: fallback, source: 'fallback' };
  }

  public async generatePersonalizedQuestion(
    params: {
      userId: string;
      skillLevel?: 'Beginner' | 'Intermediate' | 'Advanced';
      algorithmId?: string;
      topic?: string;
      completedAlgorithms?: string[];
      weakAlgorithms?: string[];
      recentErrors?: string[];
    }
  ): Promise<{
    id: string;
    algorithmId: string;
    title: string;
    question: string;
    options: { id: string; text: string; isCorrect: boolean }[];
    explanation: string;
    difficulty: string;
    pedagogicalReason: string;
    source: 'groq' | 'fallback';
  }> {
    const targetAlgo =
      params.algorithmId ||
      (params.weakAlgorithms && params.weakAlgorithms.length > 0
        ? params.weakAlgorithms[0]
        : 'merge-sort');

    const skillLevel = params.skillLevel || 'Beginner';

    if (this.groqClient) {
      try {
        const levelDirectives = {
          Beginner: 'Focus on fundamental conceptual understanding, input/output behavior, identifying the basic purpose of variables, and simple recursion or loop limits. Keep it accessible and encouraging for a beginner student.',
          Intermediate: 'Focus on loop invariants, off-by-one boundary checks, pointer manipulation (e.g. LPS rollback, mid-point calculation), and balance factors in trees.',
          Advanced: 'Focus on asymptotic and amortized tight bounds, worst-case adversarial input permutations, cache locality, multi-rotation rebalancing cascades, and space-time trade-offs.',
        }[skillLevel];

        const prompt = `Student User ID: ${params.userId}
Student Custom Level: ${skillLevel}
Target Algorithm / Topic: ${targetAlgo}
Completed Algorithms: ${(params.completedAlgorithms || []).join(', ') || 'None yet'}
Weak Topics (Struggled with): ${(params.weakAlgorithms || []).join(', ') || 'None reported'}
Recent Quiz Errors: ${(params.recentErrors || []).join('; ') || 'No recorded errors'}

Level Directive: ${levelDirectives}

Create a targeted, educational multiple-choice DSA quiz question calibrated specifically for a ${skillLevel} student.
Return strict JSON with fields: id, algorithmId, title, question, options (4 objects with { id: "a"|"b"|"c"|"d", text, isCorrect }), explanation, difficulty ("${skillLevel}"), pedagogicalReason.`;

        const completion = await this.groqClient.chat.completions.create({
          model: process.env.GROQ_MODEL || 'openai/gpt-oss-120b',
          messages: [
            {
              role: 'system',
              content:
                'You are an expert Computer Science professor generating personalized DSA practice questions for university students calibrated by difficulty level. You must output ONLY valid JSON matching the requested structure.',
            },
            { role: 'user', content: prompt },
          ],
          temperature: 0.3,
          response_format: { type: 'json_object' },
        });

        const rawContent = completion.choices[0]?.message?.content;
        if (rawContent) {
          const parsed = JSON.parse(rawContent);
          if (parsed.question && Array.isArray(parsed.options) && parsed.options.length >= 2) {
            return {
              id: parsed.id || `ai-${Date.now()}`,
              algorithmId: parsed.algorithmId || targetAlgo,
              title: parsed.title || `${targetAlgo} [${skillLevel}] Mastery Check`,
              question: parsed.question,
              options: parsed.options,
              explanation: parsed.explanation || 'No explanation provided.',
              difficulty: parsed.difficulty || skillLevel,
              pedagogicalReason:
                parsed.pedagogicalReason ||
                `Personalized for your ${skillLevel} skill level in ${targetAlgo}.`,
              source: 'groq',
            };
          }
        }
      } catch (err: any) {
        console.warn('[Groq] Personalized question generation error:', err.message);
      }
    }

    // Deterministic Fallback Question tailored by custom user level
    const levelFallbacks: Record<string, any> = {
      Beginner: {
        title: `${targetAlgo.toUpperCase()} Foundational Concept`,
        question: `For a beginner studying ${targetAlgo}, what is the fundamental operation that gives this algorithm its distinctive behavior?`,
        options: [
          { id: 'a', text: `It systematically reduces or divides the problem space step-by-step.`, isCorrect: true },
          { id: 'b', text: `It randomly guesses answers until one works.`, isCorrect: false },
          { id: 'c', text: `It ignores input size and runs in zero steps.`, isCorrect: false },
          { id: 'd', text: `It only works on arrays of size 2.`, isCorrect: false },
        ],
        explanation: `At the beginner level, the key takeaway is that ${targetAlgo} systematically transforms or traverses elements adhering to proven rules.`,
        difficulty: 'Beginner',
      },
      Intermediate: {
        title: `${targetAlgo.toUpperCase()} Invariant & Mechanics`,
        question: `In an intermediate implementation of ${targetAlgo}, what state invariant must be maintained across each iteration or recursive call?`,
        options: [
          { id: 'a', text: `The processed partition or interval guarantees structural ordering while pointers avoid redundant re-scanning.`, isCorrect: true },
          { id: 'b', text: `All pointers must point to the same memory index at all times.`, isCorrect: false },
          { id: 'c', text: `The array elements must be scrambled before every operation.`, isCorrect: false },
          { id: 'd', text: `Recursion depth must equal the maximum value in the array.`, isCorrect: false },
        ],
        explanation: `Intermediate mastery requires tracking loop invariants, pointer bounds, and partition subproblem guarantees.`,
        difficulty: 'Intermediate',
      },
      Advanced: {
        title: `${targetAlgo.toUpperCase()} Tight Bounds & Edge Cases`,
        question: `From an advanced algorithmic perspective, what adversarial input condition or amortized factor governs ${targetAlgo}'s worst-case guarantees?`,
        options: [
          { id: 'a', text: `Pathological input arrangements can trigger maximum tree height skew or maximum comparison cascades unless balanced by invariants.`, isCorrect: true },
          { id: 'b', text: `Hardware branch predictors eliminate all O(n) algorithmic overhead.`, isCorrect: false },
          { id: 'c', text: `Advanced implementations reduce all comparison-based sorting to O(1).`, isCorrect: false },
          { id: 'd', text: `Cache misses have zero impact on high-throughput traversal.`, isCorrect: false },
        ],
        explanation: `Advanced analysis demands evaluating cache locality, adversarial input configurations, and amortized rotation bounds.`,
        difficulty: 'Advanced',
      },
    };

    const chosen = levelFallbacks[skillLevel] || levelFallbacks.Beginner;

    return {
      id: `fallback-${Date.now()}`,
      algorithmId: targetAlgo,
      title: chosen.title,
      question: chosen.question,
      options: chosen.options,
      explanation: chosen.explanation,
      difficulty: chosen.difficulty,
      pedagogicalReason: `Personalized ${skillLevel} level review generated for ${targetAlgo} based on your student profile.`,
      source: 'fallback',
    };
  }

  private generateFallbackExplanation(payload: AIExplanationPayload): string {
    const step = payload.currentStep;
    if (!step) {
      return 'No active execution step found to explain.';
    }

    const algoName = payload.algorithm
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');

    let logicWhy = `Following the core invariant of ${algoName} at algorithm step ${step.algorithmLine}.`;
    if (step.comparisons) {
      logicWhy = `Evaluated comparison: ${step.comparisons.result}. This comparison determines which element is placed or which pointer advances next.`;
    } else if (step.variables?.mid !== undefined) {
      const low = step.variables.low ?? 0;
      const high = step.variables.high ?? 0;
      const mid = step.variables.mid;
      logicWhy = `Calculated midpoint: mid = floor((${low} + ${high}) / 2) = ${mid}. This divides the current subarray into two balanced subproblems.`;
    } else if (step.operation === 'SWAP') {
      logicWhy = `Swapped elements to restore the sorted partition invariant.`;
    } else if (step.operation === 'PROBE') {
      logicWhy = `Interpolated position based on relative value density: pos = ${step.variables?.pos ?? 'calculated'}.`;
    }

    const nextMove = payload.nextStep
      ? `The algorithm proceeds to **${payload.nextStep.title}**: ${payload.nextStep.description}`
      : 'This is the final state. The algorithm has completed execution successfully.';

    if (payload.question && payload.question !== 'Can you explain this step clearly and why it occurred?') {
      return `### 💬 Answer
${step.description}

### 💡 Intuition & Logic
${logicWhy}

### ⏭️ What to Watch Next
${nextMove}`;
    }

    return `### 🎯 Core Action
${step.description}

### 💡 Intuition & Logic
${logicWhy}

### ⏭️ What to Watch Next
${nextMove}`;
  }
}

export const aiService = new AIService();
